// Content data for the portfolio. Edit here to add/remove projects.
// All bilingual fields use {en, zh} — both required.

const prodData = [
  {id:'proj1',type:'drama',title:{en:'Whispers of the East',zh:'东方低语'},role:{en:'Unit Production Manager',zh:'制片主任'},desc:{en:'A 12-episode vertical short drama exploring cultural identity in modern China. Led a crew of 25+ across 3 shooting locations over 4 weeks. Managed a ¥800K budget and coordinated post-production with VFX team.',zh:'12 集竖屏短剧，探索现代中国的文化认同。带领 25+ 人团队，在 3 个拍摄地完成 4 周拍摄。管理 80 万预算，协调 VFX 后期团队。'},gallery:3,video:true},
  {id:'proj2',type:'film',title:{en:'Borderline',zh:'边界'},role:{en:'Producer / Cinematographer',zh:'制片 / 摄影指导'},desc:{en:'Award-nominated short film about immigrant experiences. Dual role as producer and DP — handled logistics, budgeting, and shot the film on BMPCC 6K with vintage anamorphic lenses.',zh:'提名奖项的移民题材短片。制片与摄影双重身份——负责统筹、预算，使用 BMPCC 6K 搭配复古变形镜头拍摄。'},gallery:4,video:true},
  {id:'proj3',type:'commercial',title:{en:'TechFlow Brand Film',zh:'TechFlow 品牌片'},role:{en:'Executive Producer',zh:'执行制片'},desc:{en:'60-second brand film for a Silicon Valley startup. Conceptualized the visual story, managed client relations, hired crew, and delivered final cut within a 2-week turnaround.',zh:'硅谷创业公司 60 秒品牌宣传片。构思视觉故事、管理客户关系、组建团队，2 周内完成交付。'},gallery:2,video:true},
  {id:'proj4',type:'drama',title:{en:'The Algorithm',zh:'算法人生'},role:{en:'Line Producer',zh:'执行制片'},desc:{en:'Sci-fi short drama series exploring AI consciousness. Managed day-to-day operations, scheduling, and kept production on track despite location challenges.',zh:'科幻短剧系列，探索 AI 意识主题。负责日常运营、排期管理，在多个拍摄地点挑战下保持制作进度。'},gallery:3,video:false},
  {id:'proj5',type:'commercial',title:{en:'Golden Gate Eats',zh:'金门美食'},role:{en:'Producer / Camera Op',zh:'制片 / 摄影'},desc:{en:'Food & lifestyle commercial series for Bay Area restaurants. Fast-paced production with same-day edits delivered for social media campaigns.',zh:'湾区餐厅美食生活类广告系列。快节奏制作，当天完成剪辑并投放社交媒体。'},gallery:2,video:true},
  {id:'proj6',type:'film',title:{en:'Silent Current',zh:'暗流'},role:{en:'Cinematographer',zh:'摄影指导'},desc:{en:'Moody noir-style short film. Shot on RED Komodo with vintage Helios lenses. Extensive color grading in DaVinci Resolve.',zh:'暗色调黑色电影风格短片。使用 RED Komodo 搭配 Helios 复古镜头拍摄。DaVinci Resolve 深度调色。'},gallery:3,video:true}
];
const devData = [
  {id:'dev1',cat:'hw',title:{en:'Smart Trash Can',zh:'智能垃圾桶'},icon:'🗑️',desc:{en:'ESP32-powered trash can with gesture sensing, auto-open lid, and Home Assistant integration.',zh:'基于 ESP32 的智能垃圾桶，支持手势感应、自动开盖，接入 Home Assistant。'},stack:['ESP32','Servo','HC-SR04','MQTT','HA'],problem:{en:'Manual trash can lids are unhygienic; commercial smart ones are overpriced.',zh:'手动垃圾桶盖不卫生，商用智能垃圾桶太贵。'},solution:{en:'ESP32 + ultrasonic sensor + servo motor. Lid opens when hand detected within 15cm, auto-closes after 5s. MQTT integration for HA tracking.',zh:'ESP32 + 超声波传感器 + 舵机。手在 15cm 内检测到自动开盖，5 秒后关闭。MQTT 接入 HA。'},result:{en:'Cost: ~$8 in parts. Running 24/7 for 6 months. Blog post went viral.',zh:'成本约 ¥60，稳定运行 6 个月。博客文章在 Maker 社区走红。'},github:'#'},
  {id:'dev2',cat:'hw',title:{en:'NFC Multi-Card Device',zh:'NFC 多卡合一设备'},icon:'💳',desc:{en:'Consolidate multiple NFC cards into one ESP32-based device with OLED display.',zh:'将多张 NFC 卡整合到一个 ESP32 设备中，OLED 屏幕选择切换。'},stack:['ESP32','PN532','OLED','3D Print','LiPo'],problem:{en:'Carrying multiple access cards is annoying.',zh:'携带多张门禁卡很烦。'},solution:{en:'ESP32 + PN532 reads/stores card UIDs. OLED + rotary encoder for selection. 3D-printed case with LiPo.',zh:'ESP32 + PN532 读取存储卡片 UID。OLED + 旋转编码器选择。3D 打印外壳 + LiPo。'},result:{en:'Cloned 5 access cards. Battery lasts ~2 weeks. Keychain-sized.',zh:'克隆 5 张门禁卡，续航约 2 周，可挂钥匙链。'},github:'#'},
  {id:'dev3',cat:'sw',title:{en:'AI Manga Pipeline',zh:'AI 漫画制作流水线'},icon:'🎨',desc:{en:'Multi-agent pipeline for vertical manga using ComfyUI + FLUX.1 + CrewAI.',zh:'基于 ComfyUI + FLUX.1 + CrewAI 的竖屏漫画多智能体流水线。'},stack:['Python','ComfyUI','FLUX.1','CrewAI','Claude API','Docker'],problem:{en:'Creating consistent manga for Douyin requires too much manual work.',zh:'为抖音短剧制作风格一致的漫画需要大量人工。'},solution:{en:'CrewAI orchestrates story generation (Claude API), character consistency (FLUX.1 + LoRA), panel layout, text overlay. ComfyUI handles image generation.',zh:'CrewAI 编排故事生成（Claude API）、角色一致性（FLUX.1 + LoRA）、分镜布局和文字排版。ComfyUI 处理图像生成。'},result:{en:'Per-episode time: 8h → 45min. 《地母七重奏》in production.',zh:'单集时间 8h → 45min。《地母七重奏》制作中。'},github:'#'},
  {id:'dev4',cat:'sw',title:{en:'Production Mgmt Tool',zh:'制片管理工具'},icon:'📋',desc:{en:'Python CLI for film production schedules, crew contacts, and budget tracking.',zh:'Python CLI 工具，管理排期、团队联系和预算。'},stack:['Python','SQLite','Click','Rich','Docker'],problem:{en:'Spreadsheet chaos on small productions.',zh:'小型制作项目表格混乱。'},solution:{en:'CLI with Rich terminal UI. SQLite stores schedules, contacts, budget. PDF export.',zh:'Rich 终端 UI + SQLite 存储排期、联系方式、预算。支持 PDF 导出。'},result:{en:'Used on 3 productions. Saved ~2h/week. Open-sourced.',zh:'已在 3 个项目中使用，每周省约 2h。已开源。'},github:'#'},
  {id:'dev5',cat:'hw',title:{en:'Gyro Game Controller',zh:'陀螺仪游戏手柄'},icon:'🎮',desc:{en:'ESP32 + MPU6050 gyro-based BLE HID game controller.',zh:'ESP32 + MPU6050 陀螺仪蓝牙游戏手柄。'},stack:['ESP32','MPU6050','BLE HID','3D Print','LiPo'],problem:{en:'Wanted motion-controlled gaming without expensive controllers.',zh:'想要体感游戏但不想买贵手柄。'},solution:{en:'ESP32 reads gyro data, maps tilt to directional input, sends via BLE HID.',zh:'ESP32 读取陀螺仪数据，映射倾斜为方向输入，BLE HID 发送。'},result:{en:'Latency <20ms. Works with any BLE device.',zh:'延迟 <20ms，兼容所有 BLE 设备。'},github:'#'},
  {id:'dev6',cat:'sw',title:{en:'Shell 30-Day Mastery',zh:'Shell 30 天精通'},icon:'$_',desc:{en:'Interactive Shell/Bash learning system with progress tracking.',zh:'Shell/Bash 交互式学习系统，带进度追踪。'},stack:['HTML','CSS','JS','Bash'],problem:{en:'No structured Shell curriculum from zero to production.',zh:'缺少从零到生产就绪的 Shell 课程。'},solution:{en:'Web-based curriculum with 30 lessons, embedded exercises, localStorage progress.',zh:'Web 课程，30 节课，内嵌练习，localStorage 进度。'},result:{en:'Completed myself. Now used by 3 friends.',zh:'自己完成全部课程，3 个朋友在用。'},github:'#'}
];
